// Modal
export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'

// Auth
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CURRENT_USER = 'CURRENT_USER'

// COURSES
export const LOADING_COURSES = 'LOADING_COURSES'
export const LOADING_CURRENT_COURSE = 'LOADING_CURRENT_COURSE'
export const FETCH_COURSES = 'FETCH_COURSES'
export const FETCH_CURRENT_COURSE = 'FETCH_CURRENT_COURSE'
export const ADD_COURSE = 'ADD_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
